### ISSUE TITLE
关于使用方法

### ISSUE THREAD

**Issue by realTaki** [lolishinshi/imsearch#7]
第一次的imsearch add-images train和后面的imsearch add-images DIR是什么关系？看起来train的图片也会被搜索，区别是？
执行多次imsearch add-images train添加训练数据，同名图片会覆盖掉吗？imsearch add-images DIR会被用于训练吗？

**Comment by KAndHisC** [comment]
还有我报出过这个错误，可能是完全没有匹配的结果？测试的图片不在训练集合中
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `256`', /localdata/workspace/imsearch/src/index.rs:152:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by KAndHisC** [comment]
我是先把大图都放进train文件夹，然后执行下面这些
imsearch add-images train
imsearch export-data
python utils/train.py K train.npy
imsearch build-index
K随便填了10，然后imsearch search-image 小图（大图的一小块）
报错的代码位置imsearch/src/index.rs:152:9如下：
```
pub fn search<M>(&self, points: &M, knn: usize) -> Vec<Vec<Neighbor>>
    where
        M: Matrix,
    {
        assert_eq!(points.width() * 8, self.d as usize);
        let mut dists = vec![0i32; points.height() * knn];
        let mut indices = vec![0i64; points.height() * knn];

        let start = Instant::now();
        unsafe {
            faiss_IndexBinary_search(
                self.index,
                points.height() as i64,
                points.as_ptr(),
                knn as i64,
                dists.as_mut_ptr(),
                indices.as_mut_ptr(),
            );
        }
```
points应该就是特征点吧？感觉是小图进去以后，一个特征点都没有，就出现了这个断言的错误？

**Comment by MichaelMai2000** [comment]
你的说法应该没错。
我用一个纯色小图可以复现这个断言错误。
```
$ RUST_BACKTRACE=full  imsearch search-image "/home/user/Pictures/black.png"
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `256`', /home/user/Applications/imsearch/src/index.rs:152:9
stack backtrace:
   0:     0x5564275f164c - std::backtrace_rs::backtrace::libunwind::trace::hf7449935ead7573e
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5564275f164c - std::backtrace_rs::backtrace::trace_unsynchronized::h221aa2d88d72372a
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5564275f164c - std::sys_common::backtrace::_print_fmt::h1c77e8983e1df895
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5564275f164c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4ec41a9a6b0d22c
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556427614cfc - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/core/src/fmt/mod.rs:1149:17
   5:     0x5564275eaaa5 - std::io::Write::write_fmt::haf74340a8cbeaa88
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/io/mod.rs:1697:15
   6:     0x5564275f3000 - std::sys_common::backtrace::_print::h2d15cd157796a64a
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5564275f3000 - std::sys_common::backtrace::print::h52d286d22e2398eb
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5564275f3000 - std::panicking::default_hook::{{closure}}::h6da08fba6306daf2
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:211:50
   9:     0x5564275f2bab - std::panicking::default_hook::h266f67a22e76b11a
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:228:9
  10:     0x5564275f36b4 - std::panicking::rust_panic_with_hook::he55698a957f4fb6d
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:606:17
  11:     0x5564275f3190 - std::panicking::begin_panic_handler::{{closure}}::h01f453c3ac181895
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:502:13
  12:     0x5564275f1af4 - std::sys_common::backtrace::__rust_end_short_backtrace::h675d77c6e5a3926d
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x5564275f30f9 - rust_begin_unwind
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:498:5
  14:     0x55642706cd11 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/core/src/panicking.rs:107:14
  15:     0x556427612c38 - core::panicking::assert_failed_inner::hc71171cfb6f4bc69
  16:     0x55642703ab6b - core::panicking::assert_failed::h95836910b4586ad2
  17:     0x5564270b2629 - imsearch::index::FaissIndex::search::hb4736c20ecefbc5e
  18:     0x5564270a0104 - imsearch::imdb::IMDB::search_des::h500d8b992cfb4f67
  19:     0x5564270a08bd - imsearch::imdb::IMDB::search::h050769121c576b3f
  20:     0x5564270965f0 - imsearch::main::he173f6de6ccaab29
  21:     0x5564270aa1e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcacabeba2921fcc9
  22:     0x55642708ec39 - std::rt::lang_start::{{closure}}::he8bf2cfccf6e21e1
  23:     0x5564275f0e91 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3ab949a23c24b3b3
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/core/src/ops/function.rs:259:13
  24:     0x5564275f0e91 - std::panicking::try::do_call::hd77545f815897665
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:406:40
  25:     0x5564275f0e91 - std::panicking::try::h7ce07831cfe77010
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:370:19
  26:     0x5564275f0e91 - std::panic::catch_unwind::h3a6382eb739fc3cb
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panic.rs:133:14
  27:     0x5564275f0e91 - std::rt::lang_start_internal::{{closure}}::ha0ce13fbefa6ed19
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/rt.rs:128:48
  28:     0x5564275f0e91 - std::panicking::try::do_call::hbacbc27e75105135
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:406:40
  29:     0x5564275f0e91 - std::panicking::try::he42832d690a14084
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panicking.rs:370:19
  30:     0x5564275f0e91 - std::panic::catch_unwind::h868b7b91fa924314
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/panic.rs:133:14
  31:     0x5564275f0e91 - std::rt::lang_start_internal::h7797a51a89d842a3
                               at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36/library/std/src/rt.rs:128:20
  32:     0x556427099922 - main
  33:     0x7f3f61ffd0b3 - __libc_start_main
  34:     0x55642708de6e - _start
  35:                0x0 - <unknown>
```

同时，你可以用
```
imsearch show-keypoints --help
```
这个功能验证你的想法。

**Comment by MichaelMai2000** [comment]
关于 `add-images` 文件索引策略，可以参考这部分代码：
https://github.com/lolishinshi/imsearch/blob/06b4c3705ec5554c7429923dbc5de5bb6fb85645/src/imdb.rs#L27-L39
https://github.com/lolishinshi/imsearch/blob/06b4c3705ec5554c7429923dbc5de5bb6fb85645/src/db/database.rs#L115-L142

并打开调试开关，观察数据库行为。
```
# 让 imsearch 打印详细日志
export RUST_LOG=debug
```

我的发现是，绝对文件路径或者文件名都不直接影响索引，索引依靠文件的哈希。
内容完全一致的文件不会重复索引，只索引最新加入的拷贝。
按文件哈希索引时，计算并存储特征。

**Comment by MichaelMai2000** [comment]
`imsearch add-images DIR` 是本质。
`imsearch add-images train` 是一个示例。
全部用法参考
```
$ imsearch add-images --help
imsearch-add-images 0.1.0
Add images to database

USAGE:
    imsearch add-images [OPTIONS] <path>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -s, --suffix <suffix>    Scan image with these suffixes [default: jpg,png]

ARGS:
    <path>    Path to an image or folder
```
和 https://github.com/lolishinshi/imsearch/blob/9b099c2c76f0af23d85849d29448074b1b3effcb/src/main.rs#L84-L112
